version: '3'

services:

  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - XDEBUG_MODE=develop,debug
    volumes:
      - ./:/var/www/html
